"""empty message

Revision ID: 29df46796522
Revises: 869128a9eb97
Create Date: 2025-05-30 16:04:57.700994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29df46796522'
down_revision = '869128a9eb97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('youtube_id', sa.String(length=255), nullable=True))
        batch_op.drop_column('spotify_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spotify_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('youtube_id')

    # ### end Alembic commands ###
