"""empty message

Revision ID: 869128a9eb97
Revises: 
Create Date: 2025-05-29 18:15:11.124609

"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy.vector

# revision identifiers, used by Alembic.
revision = '869128a9eb97'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('songs',
    sa.Column('songID', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('artist', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('spotify_id', sa.String(length=255), nullable=True),
    sa.Column('preview_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('songID')
    )
    op.create_table('song_embeddings',
    sa.Column('embeddingID', sa.Integer(), nullable=False),
    sa.Column('songID', sa.Integer(), nullable=False),
    sa.Column('dimensions', sa.Integer(), nullable=False),
    sa.Column('audioStart', sa.Float(), nullable=True),
    sa.Column('audioDuration', sa.Float(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=False),
    sa.ForeignKeyConstraint(['songID'], ['songs.songID'], ),
    sa.PrimaryKeyConstraint('embeddingID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('song_embeddings')
    op.drop_table('songs')
    # ### end Alembic commands ###
